version: '3.4'

services:
  kpiv3.webapi:
    image: ${DOCKER_REGISTRY-}kpiv3webapi

    build:
      context: .
      dockerfile: src/KpiV3.WebApi/Dockerfile

    environment:
      - ConnectionStrings__Default=Host=database;Port=5432;Database=kpi_db;UserName=kpi_user;Password=kpi_pass
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
      
      - DataInitialization__Positions__0__Name=Admin
      - DataInitialization__Positions__0__Type=Root

      - DataInitialization__Employees__1__Email=admin@kpi.com
      - DataInitialization__Employees__1__FirstName=Admin
      - DataInitialization__Employees__1__LastName=Adminovich
      - DataInitialization__Employees__1__Position=Admin

      - DataInitialization__RetryCount=5
      - DataInitialization__RetryWait=00:00:10

    ports:
      - 5000:5000

    depends_on:
      - database

  database:
    image: postgres

    ports:
      - 5432:5432

    volumes:
      - database.volume:/var/lib/postgresql/data

    environment:
      - POSTGRES_USER=kpi_user
      - POSTGRES_PASSWORD=kpi_pass
      - POSTGRES_DB=kpi_db

  flyway:
    image: flyway/flyway

    command: -url=jdbc:postgresql://database/kpi_db -user=kpi_user -password=kpi_pass -connectRetries=10 migrate

    volumes:
      - ./src/flyway/:/flyway/sql 

    depends_on:
      - database

volumes:
  database.volume: