version: '3.4'

services:
  kpiv3.webapi:
    image: ${DOCKER_REGISTRY-}kpiv3webapi

    build:
      context: .
      dockerfile: src/KpiV3.WebApi/Dockerfile

    environment:
      - ConnectionStrings__Default=Host=database;Port=5432;Database=kpi_db;UserName=kpi_user;Password=kpi_pass
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
      
      - Jwt__Issuer=Kpi
      - Jwt__Audience=Kpi
      - Jwt__TokenLifetime=1:00:00
      - Jwt__Secret=TestingPurposesOnlySecretDoNotUseInProductionPlease

      - DataInitialization__Email=admin@kpi.com
      - DataInitialization__FirstName=Admin
      - DataInitialization__LastName=Adminov
      - DataInitialization__MiddleName=Adminovich

      - Welcome__Subject=Welcome to AITU KPI
      - Welcome__BodyTemplate=Hello, {0}. You have been registered in Aitu KPI. Your password is {1}

      - S3__AccessKey=minio_user
      - S3__SecretKey=minio_pass
      - S3__Bucket=kpi
      - S3__Endpoint=http://minio:9000

    ports:
      - 5000:5000

    depends_on:
      - database

  frontend:
    image: tontea/kpi.front:latest
    container_name: frontend

    ports:
      - 80:80

  minio:
    image: minio/minio:RELEASE.2021-10-23T03-28-24Z.hotfix.f7ed7b98e
    command: server /data --console-address ":9001"
    container_name: minio
    hostname: minio
    environment:
      - MINIO_ROOT_USER=minio_user
      - MINIO_ROOT_PASSWORD=minio_pass
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - minio.volume:/data

  database:
    image: postgres
    container_name: postgres
    hostname: postgres

    ports:
      - 5432:5432

    volumes:
      - database.volume:/var/lib/postgresql/data

    environment:
      - POSTGRES_USER=kpi_user
      - POSTGRES_PASSWORD=kpi_pass
      - POSTGRES_DB=kpi_db

volumes:
  database.volume:
  minio.volume: